CREATE SEQUENCE comment_id_seq START 101;
CREATE SEQUENCE like_id_seq START 101;
CREATE SEQUENCE dislike_id_seq START 101;
CREATE SEQUENCE user_id_seq START 101;
CREATE SEQUENCE role_id_seq START 101;